use anyhow::Result;
use std::fs;
use std::path::PathBuf;

use crate::angles;
use crate::schema::FessusConfig;

pub fn generate_all(config: &FessusConfig) -> Result<()> {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    let compositor = config.fessus.compositor.as_deref().unwrap_or("sway");

    // Compositor-specific config
    match compositor {
        "hyprland" => {
            write(&home, ".config/hypr/hyprland.conf", &hyprland(config))?;
            write(&home, ".config/hypr/hyprpaper.conf", &hyprpaper(config))?;
        }
        _ => {
            // sway / fessus (default)
            write(&home, ".config/sway/config", &sway(config))?;
        }
    }

    // Shared across all compositors
    write(&home, ".config/waybar/config.jsonc",  &waybar_config(config))?;
    write(&home, ".config/waybar/style.css",     &waybar_style(config))?;
    write(&home, ".config/waybar/launch.sh",     &waybar_launch())?;
    write(&home, ".config/dunst/dunstrc",        &dunstrc(config))?;
    write(&home, ".config/eww/eww.yuck",         &eww_yuck(config))?;
    write(&home, ".config/eww/eww.scss",         &eww_scss(config))?;
    write(&home, ".config/wofi/config",          &wofi_config(config))?;
    write(&home, ".config/wofi/style.css",       &wofi_style(config))?;

    let launch = PathBuf::from(&home).join(".config/waybar/launch.sh");
    use std::os::unix::fs::PermissionsExt;
    let _ = fs::set_permissions(&launch, fs::Permissions::from_mode(0o755));

    Ok(())
}

pub fn print_all(config: &FessusConfig) -> Result<()> {
    println!("=== sway/config ===\n{}", sway(config));
    println!("=== waybar/config.jsonc ===\n{}", waybar_config(config));
    println!("=== eww/eww.yuck ===\n{}", eww_yuck(config));
    Ok(())
}

fn write(home: &str, rel_path: &str, content: &str) -> Result<()> {
    let path = PathBuf::from(home).join(rel_path);
    fs::create_dir_all(path.parent().unwrap())?;
    fs::write(&path, content)?;
    Ok(())
}

// ─── Sway ────────────────────────────────────────────────────────────────────

fn sway(c: &FessusConfig) -> String {
    let mod_key = &c.keybindings.mod_key;

    let launcher_cmd = match c.launcher.provider.as_str() {
        "anyrun" => "anyrun",
        _        => "wofi --show drun",
    };

    let autostart_lines = c.autostart.as_ref()
        .map(|a| a.apps.iter()
            .map(|app| format!("exec_always {}", app))
            .collect::<Vec<_>>()
            .join("\n"))
        .unwrap_or_default();

    let workspace_bindings: String = (1..=c.workspaces.count)
        .map(|i| format!(
            "bindsym ${mod}+{i} workspace number {i}\nbindsym ${mod}+Shift+{i} move container to workspace number {i}",
            mod = "mod", i = i
        ))
        .collect::<Vec<_>>()
        .join("\n");

    let wallpaper = c.fessus.wallpaper.replace(
        "~",
        &std::env::var("HOME").unwrap_or_default(),
    );

    format!(
r#"# Generated by fessus-init — do not edit manually
set $mod {mod_key}
set $term {terminal}
set $launcher {launcher_cmd}

font pango:{font} 10

gaps inner {gaps_inner}
gaps outer {gaps_outer}
default_border pixel {border}

seat seat0 xcursor_theme {cursor_theme} {cursor_size}

exec_always swaybg -i {wallpaper} -m fill
exec_always ~/.config/waybar/launch.sh
exec_always eww daemon

{autostart_lines}

# Core bindings
bindsym $mod+Return exec $term
bindsym $mod+d exec $launcher
bindsym $mod+q kill
bindsym $mod+Shift+r reload
bindsym $mod+f fullscreen toggle
bindsym $mod+v splith
bindsym $mod+s splitv

# Focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# Move
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Session
bindsym $mod+Shift+e exec wlogout 2>/dev/null || swaymsg exit
bindsym $mod+Shift+l exec swaylock -f -c 000000

# Radial menu toggle
bindsym $mod+r exec eww open --toggle radial

{workspace_bindings}

input type:keyboard {{
    xkb_options caps:escape
}}

input type:touchpad {{
    tap enabled
    natural_scroll enabled
}}
"#,
        mod_key         = mod_key,
        terminal        = c.keybindings.terminal,
        launcher_cmd    = launcher_cmd,
        font            = c.fessus.font,
        gaps_inner      = c.window.gaps_inner,
        gaps_outer      = c.window.gaps_outer,
        border          = c.window.border,
        cursor_theme    = c.fessus.cursor_theme,
        cursor_size     = c.fessus.cursor_size,
        wallpaper       = wallpaper,
        autostart_lines = autostart_lines,
        workspace_bindings = workspace_bindings,
    )
}

// ─── Hyprland ─────────────────────────────────────────────────────────────────

fn hyprland(c: &FessusConfig) -> String {
    let mod_key = &c.keybindings.mod_key;

    let autostart_lines = c.autostart.as_ref()
        .map(|a| a.apps.iter()
            .map(|app| format!("exec-once = {}", app))
            .collect::<Vec<_>>().join("\n"))
        .unwrap_or_default();

    let workspace_binds: String = (1..=c.workspaces.count)
        .flat_map(|i| [
            format!("bind = $mod, {i}, workspace, {i}"),
            format!("bind = $mod SHIFT, {i}, movetoworkspace, {i}"),
        ])
        .collect::<Vec<_>>().join("\n");

    let accent_no_hash = c.fessus.accent_color.trim_start_matches('#');
    let wallpaper = c.fessus.wallpaper.replace('~',
        &std::env::var("HOME").unwrap_or_default());

    format!(
r#"# Generated by fessus-init — do not edit manually

monitor = , preferred, auto, 1

$mod      = {mod_key}
$term     = {terminal}
$launcher = wofi --show drun

input {{
    kb_layout  = us
    follow_mouse = 1
    sensitivity  = 0

    touchpad {{
        natural_scroll   = yes
        tap-to-click     = yes
        disable_while_typing = yes
    }}
}}

general {{
    gaps_in  = {gaps_inner}
    gaps_out = {gaps_outer}
    border_size = {border}
    col.active_border   = rgba({accent}ee)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}}

decoration {{
    rounding = 8
    blur {{
        enabled = yes
        size    = 6
        passes  = 2
    }}
    shadow {{
        enabled = yes
        range   = 8
        render_power = 2
        color   = rgba(00000044)
    }}
}}

animations {{
    enabled = yes
    bezier  = smooth, 0.05, 0.9, 0.1, 1.05
    animation = windows,    1, 6,  smooth
    animation = windowsOut, 1, 5,  default, popin 80%
    animation = fade,       1, 6,  default
    animation = workspaces, 1, 5,  default
}}

dwindle {{
    pseudotile    = yes
    preserve_split = yes
}}

cursor {{
    no_hardware_cursors = false
}}

env = XCURSOR_THEME, {cursor_theme}
env = XCURSOR_SIZE,  {cursor_size}

# Autostart
exec-once = waybar
exec-once = dunst
exec-once = swww-daemon
exec-once = swww img {wallpaper} --transition-type fade
exec-once = eww daemon
{autostart_lines}

# Core bindings
bind = $mod,       Return,  exec, $term
bind = $mod,       D,       exec, $launcher
bind = $mod,       Q,       killactive
bind = $mod,       F,       fullscreen
bind = $mod,       R,       exec, eww open --toggle radial
bind = $mod SHIFT, L,       exec, hyprlock
bind = $mod SHIFT, E,       exec, wlogout 2>/dev/null || hyprctl dispatch exit 0
bind = $mod,       V,       togglefloating

# Focus
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

# Move
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

# Resize with mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

{workspace_binds}
"#,
        mod_key         = mod_key,
        terminal        = c.keybindings.terminal,
        gaps_inner      = c.window.gaps_inner,
        gaps_outer      = c.window.gaps_outer,
        border          = c.window.border,
        accent          = accent_no_hash,
        cursor_theme    = c.fessus.cursor_theme,
        cursor_size     = c.fessus.cursor_size,
        wallpaper       = wallpaper,
        autostart_lines = autostart_lines,
        workspace_binds = workspace_binds,
    )
}

fn hyprpaper(c: &FessusConfig) -> String {
    let wallpaper = c.fessus.wallpaper.replace('~',
        &std::env::var("HOME").unwrap_or_default());
    format!(
        "preload = {wp}\nwallpaper = ,{wp}\nsplash = false\n",
        wp = wallpaper
    )
}

// ─── Waybar launch script ────────────────────────────────────────────────────

fn waybar_launch() -> String {
    r#"#!/bin/sh
# Kill any existing waybar before relaunching (used by sway reload)
pkill -x waybar 2>/dev/null
sleep 0.1
exec waybar
"#.to_string()
}

// ─── Waybar ───────────────────────────────────────────────────────────────────

fn waybar_config(c: &FessusConfig) -> String {
    let mut right_modules: Vec<&str> = vec![];
    if c.bar.show_bluetooth { right_modules.push("\"bluetooth\""); }
    if c.bar.show_network   { right_modules.push("\"network\""); }
    if c.bar.show_battery   { right_modules.push("\"battery\""); }
    if c.bar.show_tray      { right_modules.push("\"tray\""); }
    right_modules.push("\"clock\"");

    format!(
r#"{{
  "layer": "top",
  "position": "{position}",
  "height": 32,
  "spacing": 4,
  "modules-left": ["sway/workspaces"],
  "modules-center": [],
  "modules-right": [{right}],
  "sway/workspaces": {{
    "disable-scroll": true,
    "all-outputs": true
  }},
  "clock": {{
    "format": "{clock_format}",
    "tooltip": false
  }},
  "battery": {{
    "format": "  {{capacity}}%",
    "format-charging": "  {{capacity}}%"
  }},
  "network": {{
    "format-wifi": "  {{essid}}",
    "format-ethernet": "  connected",
    "format-disconnected": "  offline",
    "tooltip": false
  }},
  "bluetooth": {{
    "format": " ",
    "format-connected": "  {{device_alias}}",
    "tooltip": false
  }},
  "tray": {{
    "spacing": 8
  }}
}}
"#,
        position     = c.bar.position,
        clock_format = c.bar.clock_format,
        right        = right_modules.join(", "),
    )
}

fn waybar_style(c: &FessusConfig) -> String {
    let (bg, fg, surface) = theme_colors(&c.fessus.theme);
    format!(
r#"* {{
  font-family: {font};
  font-size: 13px;
  border: none;
  border-radius: 0;
}}

window#waybar {{
  background: {bg};
  color: {fg};
}}

#workspaces button {{
  padding: 0 8px;
  color: {fg};
  background: transparent;
}}

#workspaces button.focused {{
  color: {accent};
  border-bottom: 2px solid {accent};
}}

#clock, #battery, #network, #bluetooth, #tray {{
  padding: 0 12px;
  color: {fg};
}}
"#,
        font   = c.fessus.font,
        bg     = bg,
        fg     = fg,
        accent = c.fessus.accent_color,
    )
}

// ─── Dunst ───────────────────────────────────────────────────────────────────

fn dunstrc(c: &FessusConfig) -> String {
    let (bg, fg, _) = theme_colors(&c.fessus.theme);
    let origin = dunst_origin(&c.notifications.position);

    format!(
r##"[global]
    font = {font} 11
    origin = {origin}
    notification_limit = {max_visible}
    timeout = {timeout}
    background = "{bg}"
    foreground = "{fg}"
    frame_color = "{accent}"
    frame_width = 2
    corner_radius = 8
    padding = 12
    horizontal_padding = 12
    gap_size = 8
    icon_theme = {icon_theme}
    enable_recursive_icon_lookup = true
    min_icon_size = 32
    max_icon_size = 64

[urgency_low]
    timeout = {timeout}

[urgency_normal]
    timeout = {timeout}

[urgency_critical]
    frame_color = "#ff5555"
    timeout = 0
"##,
        font        = c.fessus.font,
        origin      = origin,
        max_visible = c.notifications.max_visible,
        timeout     = c.notifications.timeout / 1000,
        bg          = bg,
        fg          = fg,
        accent      = c.fessus.accent_color,
        icon_theme  = c.fessus.icon_theme,
    )
}

fn dunst_origin(position: &str) -> &str {
    match position {
        "top-left"     => "top-left",
        "top-right"    => "top-right",
        "bottom-left"  => "bottom-left",
        "bottom-right" => "bottom-right",
        _              => "top-right",
    }
}

// ─── Eww radial menu ─────────────────────────────────────────────────────────

fn eww_yuck(c: &FessusConfig) -> String {
    let anchor = corner_to_eww_anchor(&c.radial.corner);
    let (x, y) = corner_to_xy(&c.radial.corner);

    let app_buttons: String = c.radial.pinned.iter().enumerate()
        .map(|(i, app)| {
            let icon = app_icon(app);
            format!(
                "    (button :class \"app-btn app-btn-{i}\" :onclick \"exec {app}\" \"{icon}\")",
                i = i, app = app, icon = icon,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
r#"(defwindow radial
  :monitor 0
  :geometry (geometry :x "{x}" :y "{y}" :width "280px" :height "280px" :anchor "{anchor}")
  :stacking "overlay"
  :exclusive false
  :visible false
  (radial-menu))

(defwidget radial-menu []
  (box :class "radial-container"
    (button :class "center-btn"
            :onclick "wofi --show drun"
            "")
{app_buttons}
  ))
"#,
        x           = x,
        y           = y,
        anchor      = anchor,
        app_buttons = app_buttons,
    )
}

fn eww_scss(c: &FessusConfig) -> String {
    let (bg, fg, surface) = theme_colors(&c.fessus.theme);
    let angles = angles::calculate(c.radial.pinned.len());
    let radius = 8.0_f64;

    let app_btn_styles: String = angles.iter().enumerate()
        .map(|(i, &angle)| {
            let transform = angles::css_transform(angle, radius);
            format!(
r#"  .app-btn-{i} {{
    transform: {transform};
  }}"#,
                i = i, transform = transform,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
r#"* {{
  font-family: {font};
  all: unset;
}}

.radial-container {{
  position: relative;
  width: 280px;
  height: 280px;
  background: transparent;
}}

.center-btn {{
  position: absolute;
  bottom: 0;
  left: 0;
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: {accent};
  color: {fg};
  font-size: 22px;
  border: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.15s ease;

  &:hover {{
    background: {surface};
  }}
}}

.app-btn {{
  position: absolute;
  bottom: 10px;
  left: 10px;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  background: {surface};
  color: {fg};
  font-size: 18px;
  border: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.15s ease;
  transform-origin: center center;

  &:hover {{
    background: {accent};
  }}
}}

{app_btn_styles}
"#,
        font           = c.fessus.font,
        accent         = c.fessus.accent_color,
        fg             = fg,
        surface        = surface,
        app_btn_styles = app_btn_styles,
    )
}

// ─── Wofi ────────────────────────────────────────────────────────────────────

fn wofi_config(_c: &FessusConfig) -> String {
    r#"show=drun
width=480
height=360
allow_images=true
insensitive=true
prompt=Search...
"#.to_string()
}

fn wofi_style(c: &FessusConfig) -> String {
    let (bg, fg, surface) = theme_colors(&c.fessus.theme);
    format!(
r#"* {{
  font-family: {font};
}}

window {{
  background-color: {bg};
  border-radius: 12px;
  border: 2px solid {accent};
}}

#input {{
  background: {surface};
  color: {fg};
  border-radius: 8px;
  border: none;
  padding: 10px 14px;
  margin: 10px;
}}

#entry:selected {{
  background: {accent};
  border-radius: 8px;
}}
"#,
        font    = c.fessus.font,
        bg      = bg,
        fg      = fg,
        surface = surface,
        accent  = c.fessus.accent_color,
    )
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

fn theme_colors(theme: &str) -> (&'static str, &'static str, &'static str) {
    match theme {
        "light" => ("#eff1f5", "#4c4f69", "#dce0e8"),
        _       => ("#1e1e2e", "#cdd6f4", "#313244"),
    }
}

fn corner_to_eww_anchor(corner: &str) -> &str {
    match corner {
        "top-left"     => "top left",
        "top-right"    => "top right",
        "bottom-right" => "bottom right",
        _              => "bottom left",
    }
}

fn corner_to_xy(corner: &str) -> (&str, &str) {
    match corner {
        "top-left"     => ("0px", "0px"),
        "top-right"    => ("0px", "0px"),
        "bottom-right" => ("0px", "0px"),
        _              => ("0px", "0px"),
    }
}

fn app_icon(app: &str) -> &str {
    match app {
        "firefox"         => "",
        "zen-browser"     => "",
        "librewolf"       => "",
        "kitty"           => "",
        "thunar"          => "",
        "mousepad"        => "",
        "mpv"             => "",
        "imv"             => "",
        "zathura"         => "",
        "btop"            => "",
        "xarchiver"       => "",
        "blueman-manager" => "",
        "qalculate-gtk"   => "",
        "wf-recorder"     => "",
        "gimp"            => "",
        "inkscape"        => "",
        "vscode"          => "",
        "code"            => "",
        _                 => "",
    }
}
