---
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: EFI

# Swap partition — create if RAM < 8GB
ensureSuspendToDisk: true
neverCreateSwap: false

defaultFileSystemType: ext4

availableFileSystemTypes:
  - ext4
  - btrfs
  - xfs
