---
defaultGroups:
  - wheel
  - audio
  - video
  - input
  - seat
  - storage
  - network
  - optical

autologinGroup: autologin
doAutologin: false

sudoersGroup: wheel
setRootPassword: false

# Password requirements
passwordRequirements:
  minLength: 6
  maxLength: -1
