timeout: 5
term_wallpaper_style: centered

/MycelOS Live
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=MYCELOS rd.live.image rd.live.squashimg=/MycelOS/airootfs.sfs quiet splash
    module_path: boot():/boot/initramfs.img

/MycelOS Live (copy to RAM)
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=MYCELOS rd.live.image rd.live.squashimg=/MycelOS/airootfs.sfs rd.live.ram quiet splash
    module_path: boot():/boot/initramfs.img

/MycelOS Live (safe mode)
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=MYCELOS rd.live.image rd.live.squashimg=/MycelOS/airootfs.sfs nomodeset
    module_path: boot():/boot/initramfs.img
