timeout: 5

/MycelOS Live
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=@CDLABEL@ rd.live.image rd.live.overlay.overlayfs=1 rd.live.dir=MycelOS rd.live.squashimg=airootfs.sfs quiet splash
    module_path: boot():/boot/initramfs.img

/MycelOS Live (copy to RAM)
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=@CDLABEL@ rd.live.image rd.live.overlay.overlayfs=1 rd.live.dir=MycelOS rd.live.squashimg=airootfs.sfs rd.live.ram quiet splash
    module_path: boot():/boot/initramfs.img

/MycelOS Live (safe mode)
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=@CDLABEL@ rd.live.image rd.live.overlay.overlayfs=1 rd.live.dir=MycelOS rd.live.squashimg=airootfs.sfs nomodeset
    module_path: boot():/boot/initramfs.img
