# MycelOS Calamares configuration

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - shellbrowser
    - users
    - partition
    - summary

  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - mycelos-cleanup
    - mycel-seed
    - limine
    - umount

branding: mycel

prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
